-- MySQL Script generated by MySQL Workbench
-- 12/02/15 09:27:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema popote
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `popote` ;

-- -----------------------------------------------------
-- Schema popote
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `popote` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `popote` ;

-- -----------------------------------------------------
-- Table `popote`.`membres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popote`.`membres` ;

CREATE TABLE IF NOT EXISTS `popote`.`membres` (
  `id_membre` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(10) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(30) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_membre`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popote`.`categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popote`.`categorie` ;

CREATE TABLE IF NOT EXISTS `popote`.`categorie` (
  `id_cat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_cat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popote`.`sous_categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popote`.`sous_categorie` ;

CREATE TABLE IF NOT EXISTS `popote`.`sous_categorie` (
  `id_ss_cat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `description` VARCHAR(50) NOT NULL,
  `id_cat` INT NOT NULL,
  PRIMARY KEY (`id_ss_cat`),
  INDEX `idx_fk_id_categorie_ss_cat` (`id_cat` ASC),
  CONSTRAINT `fk_id_categorie_ss_cat`
    FOREIGN KEY (`id_cat`)
    REFERENCES `popote`.`categorie` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popote`.`recettes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popote`.`recettes` ;

CREATE TABLE IF NOT EXISTS `popote`.`recettes` (
  `id_recette` INT NOT NULL AUTO_INCREMENT,
  `id_membre` INT NOT NULL,
  `titre` VARCHAR(50) NOT NULL,
  `nb_pers` INT NOT NULL,
  `cat_prix` VARCHAR(20) NOT NULL,
  `cat_diff` VARCHAR(20) NOT NULL,
  `note` INT NOT NULL,
  `nb_votes` INT NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `preparation` VARCHAR(100) NOT NULL,
  `cuisson` VARCHAR(100) NOT NULL,
  `conseil` VARCHAR(250) NOT NULL,
  `id_cat` INT NOT NULL,
  `id_ss_cat` INT NOT NULL,
  PRIMARY KEY (`id_recette`),
  INDEX `idx_fk_id_membre_recettes` (`id_membre` ASC),
  INDEX `idx_fk_id_categorie_recettes` (`id_cat` ASC),
  INDEX `idx_fk_id_ss_categorie_recettes` (`id_ss_cat` ASC),
  CONSTRAINT `fk_id_membre_recettes`
    FOREIGN KEY (`id_membre`)
    REFERENCES `popote`.`membres` (`id_membre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_categorie_recettes`
    FOREIGN KEY (`id_cat`)
    REFERENCES `popote`.`categorie` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_ss_categorie_recettes`
    FOREIGN KEY (`id_ss_cat`)
    REFERENCES `popote`.`sous_categorie` (`id_ss_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popote`.`commentaires`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popote`.`commentaires` ;

CREATE TABLE IF NOT EXISTS `popote`.`commentaires` (
  `id_commentaire` INT NOT NULL AUTO_INCREMENT,
  `id_recette` INT NOT NULL,
  `id_membre` INT NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_commentaire`),
  INDEX `idx_fk_id_recette_commentaires` (`id_recette` ASC),
  INDEX `idx_fk_id_membre_commentaires` (`id_membre` ASC),
  CONSTRAINT `fk_id_recette_commentaires`
    FOREIGN KEY (`id_recette`)
    REFERENCES `popote`.`recettes` (`id_recette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_membre_commentaires`
    FOREIGN KEY (`id_membre`)
    REFERENCES `popote`.`membres` (`id_membre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popote`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popote`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `popote`.`ingredients` (
  `id_ingredient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `couleur` VARCHAR(50) NOT NULL,
  `type` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_ingredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popote`.`constituants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popote`.`constituants` ;

CREATE TABLE IF NOT EXISTS `popote`.`constituants` (
  `id_constituant` INT NOT NULL AUTO_INCREMENT,
  `id_recette` INT NOT NULL,
  `id_ingredient` INT NOT NULL,
  `quantite` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_constituant`),
  INDEX `idx_fk_id_recette_constituants` (`id_recette` ASC),
  INDEX `idx_fk_id_ingredient_constituants` (`id_ingredient` ASC),
  CONSTRAINT `fk_id_recette_constituants`
    FOREIGN KEY (`id_recette`)
    REFERENCES `popote`.`recettes` (`id_recette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_ingredient_constituants`
    FOREIGN KEY (`id_ingredient`)
    REFERENCES `popote`.`ingredients` (`id_ingredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `popote`.`photos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `popote`.`photos` ;

CREATE TABLE IF NOT EXISTS `popote`.`photos` (
  `id_photo` INT NOT NULL AUTO_INCREMENT,
  `id_recette` INT NOT NULL,
  `lien` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_photo`),
  INDEX `idx_fk_id_recette_photo` (`id_recette` ASC),
  CONSTRAINT `fk_id_recette_photo`
    FOREIGN KEY (`id_recette`)
    REFERENCES `popote`.`recettes` (`id_recette`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
